### ISSUE TITLE
I really ment it. Make this github repository private

### ISSUE THREAD

**Issue by Xeros08** [josh-m/RW-Decompile#1]
I don't think Ludeon likes the decompiled source code of it's game to be so accesible online.
I really mean it, make this repository private, just in case.

**Comment by josh-m** [comment]
If I get a request from Tynan to take it down, I'll happily do so. He's obviously aware that anyone can decompile the code, it's really easy to do. This was simply meant as a modding resource so you could track changes between releases.

Alas, the repo is out of date as I haven't posted any decompiles since 1.0.

I appreciate your concern for the excellent folks at Ludeon, but I highly doubt they care about this.

**Comment by josh-m** [comment]
Also, I'm aware of the old "controversy" regarding the source code that occurred after a misguided RPS article was published in 2016. I've also read Tynan's responses, and he never asked for people to stop decompiling the code. He was just frustrated by the poor reading of it, and the added comments and changes in the pseudocode that could be misinterpreted as his own work.

**Comment by Sepphoris** [comment]
> I don't think Ludeon likes the decompiled source code of it's game to be so accesible online.
> I really mean it, make this repository private, just in case.

This has been up for years, and Ludeon likely knows about it since Tynan is semi-interactive with the modding community, and how the modding community uses this repo to help understand how to code properly. This would have been down a long time ago if there was an issue.
